### ISSUE TITLE
Exclude several IPs from brutforce protection

### ISSUE THREAD

**Issue by aWuttig** [AOEpeople/felogin_bruteforce_protection#1]
* we have the problem that some customers surf via internal proxy server
* so they have only one IP for us 
* in case of an fail login we will lock all users behind the proxy
* our solution is to configure ip adresses or a range of ip adresses wihtin the extension to prevent blocking them
* add field to extConf to specify several ip adresses which should be excluded from brutforce protection

**Comment by vdespa** [comment]
Feel free to provide a solution and to send us a Pull Request. Have a look at the FeLoginBruteForceApi and find a way to integrate with it. 

Thanks in advance!

**Comment by kschu91** [comment]
added feature in current master ;)

**Comment by portrino-dev** [comment]
Oh i will test the new feature soon!!! Thanks!
