### ISSUE TITLE
Question on compatibility with TYPO3 v9

### ISSUE THREAD

**Issue by dsg1-wolf** [AOEpeople/felogin_bruteforce_protection#21]
I just have a quick question on the compatibility of this extension.

In TER, the changelog for v2.1.0 says it added compatibility for TYPO3 v9, yet the two more current versions do not seem to show up as compatible with v9.

So, is only v2.1.0 compatible with TYPO3 v9 and thereafter compat was dropped again or is simply the TER not up to date here?

Thx in advance!
Tom

**Comment by tomasnorre** [comment]
Hi @dsg1-wolf 

That sounds funny... I would have too look into that. 
Thanks for reaching out.

**Comment by tomasnorre** [comment]
The is a TYPO3V9 branch, does that work for you? 

I would need to check what happened to our releases. looked like we did something not that logic..

**Comment by dsg1-wolf** [comment]
I might check the branch out then – getting it via TER would've been a charm, but I take what I can get. :)

Oddly enough, the TER search results show v2.1.2 as compatible with TYPO3 v9, too, whilst the detail page on your extension does not.

**Comment by tomasnorre** [comment]
I'll check it out as well.

**Comment by TomSchenk** [comment]
Hi @dsg1-wolf,
is this still relevant?

**Comment by tlayh** [comment]
Closing. Nobody wants TYPO3v9 anyway :)
