### ISSUE TITLE
devlog is deprecated since v8

### ISSUE THREAD

**Issue by rogueonepalimpalim** [AOEpeople/felogin_bruteforce_protection#27]
See https://extensions.typo3.org/extension/devlog

Wanted to install the extension for v10.4.x. Doesn't work and doesn't provide logs. Any ideas how to protect the fe_login anyway, without upgrading to v11.x?

**Comment by TomSchenk** [comment]
Sorry, but we are only using 11.x+ systems, unfortunately we will not provide any fixes for this in minor 11.x versions.
Feel free to provide a pull request :-)
