### ISSUE TITLE
Typo3 10.4.36 - Login with nonexistent user gives TypeError in PasswordHashFactory::getDefaultHashInstance()

### ISSUE THREAD

**Issue by fennecgit** [AOEpeople/felogin_bruteforce_protection#28]
After installing the extension and trying to login on an page with felogin plugin with an user that doesn't exist you get following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory::getDefaultHashInstance() must be of the type string, null given, called in ...typo3/sysext/core/Classes/Authentication/AuthenticationService.php on line 204.

I've tested this with Typo3 10.4.32 and 10.4.36. After uninstalling the extension the felogin plugin works as it should.

Thank you in advance for handling my request.

**Comment by Mainbird** [comment]
I can confirm this issue we are running into the same struggle with TYPO3 10.4.36.

**Comment by fennecgit** [comment]
Jeah,
Yes, that's it. I've tested in in Typo3 10.4.36 and version 10.0.0 of felogin_bruteforce_protection. 
Thank you a lot. 👍
