### ISSUE TITLE
TCA Configuration deprecated

### ISSUE THREAD

**Issue by aWuttig** [AOEpeople/felogin_bruteforce_protection#3]
TYPO3 supports TCA configuration in one single file ("tx_feloginbruteforceprotection_domain_model_entry"). Here is the patch which does the job for you. Without configuration of TCA in a single file the extension does not work for me :/

**Comment by aWuttig** [comment]
Cannot upload patch file unfortunately :/

**Comment by vdespa** [comment]
Hi, thanks for your report and fix. 

Please submit a PR (Pull Request) so that we can easily analyse and merge it. You can create a PR after you fork this project and make a commit. For easy changes you can just use the GitHub GUI to edit a file and submit the PR.

**Comment by vdespa** [comment]
Thanks for your PR. Closing this issue.

**Comment by vdespa** [comment]
@aWuttig We merged your changes. Please test again against our master branch. Thanks.
