### ISSUE TITLE
Exception after installing TER Version ( 	10.0.5 )

### ISSUE THREAD

**Issue by BenjaminBeck** [AOEpeople/felogin_bruteforce_protection#31]
Can someone confirm this? 

Its a bigger Installation with TYPO3 11.5.26. It could be a incompatibility with another extension..

![image](https://github.com/AOEpeople/felogin_bruteforce_protection/assets/1185872/986f4df6-b54f-40b7-a8c5-b76d5a77ff65)

**Comment by TomSchenk** [comment]
Hi @BenjaminBeck,
looks like the user object might be inconsistent?!
Unfortunately, with the present information, we can not reproduce this error.

**Comment by BenjaminBeck** [comment]
Thanks for the feedback @TomSchenk 
I notices shortly after testing this extension that TYPO3 has a similar feature now in the core:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Feature-93825-RateLimitingForFailedLogins.html

This is good enough for me so i did no further debugging.
