### ISSUE TITLE
Exception "The default controller for extension "X" and plugin "Y" can not be determined" in TYPO3 V11

### ISSUE THREAD

**Issue by carsten-wilhelm** [AOEpeople/felogin_bruteforce_protection#32]
I have an issue installing the extension in TYPO3 V11.

When added with composer, I get exceptions in frontend - for our own extensions, but also plugins from extensions like indexed search.
"The default controller for extension "X" and plugin "Y" can not be determined

Root cause analysis - when the plugin is looked up by extbase, the configuration is from a BE request, therefore no plugin is found at all.
Debugging brought me to the RestrictionService:
https://github.com/AOEpeople/felogin_bruteforce_protection/blob/main/Classes/Domain/Service/RestrictionService.php

When I comment out lines 110/111, so that PersistenceManager and EntryRepository are not includes, the exceptions are gone. Adding any of the two lines will get the extension back.

We upgraded from an older TYPO3 version and tries to include this extension in V11, maybe it might be related to some older stuff in our code, but definitely it orks without the extension installed.

**Comment by carsten-wilhelm** [comment]
I think I found more infos here - the extension uses a "postUserLookUp" hook, which is triggered in the FrontendUserAuthenticator middleware. This runs before the TypoScriptFrontendInitialization.
In V11, all initializations of Extbase repositories before tsfe will fail - so currently I have no idea why nobody else would have this issue in V11.

**Comment by carsten-wilhelm** [comment]
Sorry, no longer relevant - V11 has its own rate limiter

**Comment by tlayh** [comment]
Sorry for the late response. As far as I understand you, I can close this issue. But thanks for reporting.
