### ISSUE TITLE
Extend the plugin to restrict login to IP address ranges

### ISSUE THREAD

**Issue by taalas** [AOEpeople/felogin_bruteforce_protection#9]
In order to further secure forced login attempts it might be benificial to add an option to restrict login to a specific IP address range for the given user or control depending options from this information (like restricting the login attempts to a given number if from/not from a specific IP range).

**Comment by aWuttig** [comment]
This is possible, but unfortunatly not documented yet. Just use the CIRD format to determine IP ranges: e.g.: 192.168.100.14/24

See this code fore more details:
https://github.com/AOEpeople/felogin_bruteforce_protection/blob/22e9725ab4d3c5566ca871f703e4b0056e94753a/Classes/Domain/Service/RestrictionIdentifierClientIp.php#L76
